### ISSUE TITLE
SpringSecurityOauthController::linkAccount Assumes that the user name is command.username

### ISSUE THREAD

**Issue by monksy** [enr/grails-spring-security-oauth#13]
I'm using Google Oauth, and after going to the link or create account page from the SpringSecurityOauth page, I'm getting the following exception

    org.codehaus.groovy.grails.exceptions.InvalidPropertyException: No property found for name [username] for class [class com.eventrosity.Person]
    	at org.grails.datastore.gorm.GormStaticApi.methodMissing(GormStaticApi.groovy:104)
    	at             grails.plugin.springsecurity.oauth.SpringSecurityOAuthController$_linkAccount_closure1.doCall(SpringSecurityOAuthController.groovy:133)

It appears that the method does not respect the property: userLookup.usernamePropertyName

**Comment by enr** [comment]
Hi @monksy ,

thank you very much for the notice, please verify if my last commit fixes it for you.

Cheers, Enrico

**Comment by monksy** [comment]
How would I modify my BuildConfig to verify this?

**Comment by enr** [comment]
You should use:

```
compile ':spring-security-oauth:2.1.0-SNAPSHOT'
```
Probably is better to clean the grails cache and target directory to ensure to download the last version (just published).

**Comment by monksy** [comment]
It works. Thanks!

**Comment by enr** [comment]
Glad to help, thanks for pointing it out.
