### ISSUE TITLE
Not able to start application - 

### ISSUE THREAD

**Issue by rahulcse1** [enr/grails-spring-security-oauth#16]
Step i am following -
1- create fresh "social-login" app to test plugin. my grails version is 2.2.4 and spring security version is compile ":spring-security-core:1.2.7.3"
2- Added compile ':spring-security-oauth:2.0.2'
		compile ":spring-security-oauth-facebook:0.2"
		compile ":spring-security-oauth-google:0.3.1"
		compile ":spring-security-oauth-linkedin:0.2"
		compile ":spring-security-oauth-yahoo:0.2" 
in build config.
3- when am i trying to run app or refreshing dependency getting below -

| Downloading: spring-security-oauth-facebook-0.2.zip.sha1
| Downloading: spring-security-oauth-linkedin-0.2.zip.sha1
| Downloading: spring-security-oauth-yahoo-0.2.zip.sha1.
| Environment set to development.....
| Installing zip spring-security-oauth-facebook-0.2.zip.....
| Installed plugin spring-security-oauth-facebook-0.2.....
| Installing zip spring-security-oauth-2.1.0-RC4.zip.....
| Installed plugin spring-security-oauth-2.1.0-RC4
*********************************************************************
* You've installed the Spring Security OAuth plugin.                *
*                                                                   *
* Next run the "grails s2-init-oauth" script to configure plugin.   *
*                                                                   *
*********************************************************************
| Installed plugin spring-security-oauth-2.1.0-RC4....
| Installing zip spring-security-core-2.0-RC3.zip.....
| Installed plugin spring-security-core-2.0-RC3
*******************************************************
* You've installed the Spring Security Core plugin.   *
*                                                     *
* Next run the "s2-quickstart" script to initialize   *
* Spring Security and create your domain classes.     *
*                                                     *
*******************************************************
| Installed plugin spring-security-core-2.0-RC3....
| Installing zip oauth-2.5.zip.....
| Installed plugin oauth-2.5...
| Installing zip codenarc-0.21.zip.....
| Installed plugin codenarc-0.21...
| Installing zip spring-security-oauth-google-0.3.1.zip.....
| Installed plugin spring-security-oauth-google-0.3.1...
| Installing zip spring-security-oauth-linkedin-0.2.zip.....
| Installed plugin spring-security-oauth-linkedin-0.2...
| Installing zip spring-security-oauth-yahoo-0.2.zip.....
| Installed plugin spring-security-oauth-yahoo-0.2....
| <strong>
Error Fatal error during compilation org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/C:/Users/amar/.grails/ivy-cache/org.grails/grails-core/jars/grails-core-2.2.4.jar!/org/codehaus/groovy/grails/compiler/DirectoryWatcher$FileChangeListener.class]; nested exception is java.lang.NoClassDefFoundError: org/springframework/core/type/classreading/AnnotationMetadataReadingVisitor (Use --stacktrace to see the full trace)
| Error org.codehaus.groovy.grails.cli.ScriptExitException
| Error 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
| Error 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
| Error 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
| Error 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
| Error 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
| Error 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
| Error 	at o .....

</strong>

**Comment by enr** [comment]
Hi @rahulcse1 , thank you for point out this.
I suspect it could be a problem related to dependencies.
This plugin, as `v2.0.2` is built against Grails 2.3.3 and has dependency 
`compile ":spring-security-core:2.0-RC2"`
If you can, I suggest to change Grails and SSC to these versions, otherwise you could try an older version of the plugin.
Sorry but at the moment I don't have much time to dedicate to this plugin and to investigate deeper this error.
Cheers, Enrico

**Comment by rahulcse1** [comment]
Thanks @enr  , could you please suggest me ? which version would be fine for my setting ?

**Comment by enr** [comment]
Grails `2.3.3` and spring-security-core `2.0-RC2`
